### ISSUE TITLE
W2 Make the repository a python package

### ISSUE THREAD

**Issue by datadej** [dostodejski/spd_birthdays#4]
Homework Week 2 - Task 1
1. Create a separate folder
2.  Add an `__init__.py` file to it
3. Modify the main.py script if needed
Use this as an example: https://github.com/swdevel-lab-hfarm/mypackage

**Comment by GianlucaBasso** [comment]
issue solved with commit:
https://github.com/dostodejski/spd_birthdays/commit/075d2e8f0e31cd6efc531e7de2208248dc48cb50
